version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - ineffassign
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-strings
      - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
